%function [head,tail] = function [flippedData] = flipDLThorizontal(data,imageheight)
%
%This function takes coordinates generated by DLTdv5, which has an origin
%in the bottom left-hand corner, and performs a horizontal reflection to
%place them in a MATLAB matrix coordinate system, which has an origin in
%the upper left-hand corner (or vice versa!).
%
%Inputs:
%data - x,y pixel coordinates of all points (N) that need to be flipped (1 row,
%2N col)
%imageheight - the pixel height of the y axis of the video
%
%Outputs:
%flippedData - flipped x,y pixel coordinates of all points (1 row, 2N col)
%
%Katherine Znotinas March 23 2018
%Modified to include more than 1 point Kathleen Foster - May 31, 2018
%Debugged Keegan Lutek
%Minor edits Em Standen June 28 2020

function [flippedData] = flipDLThorizontal(data,imageheight)

    flip = imageheight/2;

%     check = find(isnan(data));
%     if ~isempty(check)
%         NaN_error = 'Missing DLT point';
%         error(NaN_error);
%     end
    
    for p=1:length(data)/2
        if ~isnan(data(p*2))
            if data(p*2) < flip
                flippedData(p*2) = flip + (flip-data(p*2));
            end
            if data(p*2) > flip   
                flippedData(p*2) = flip - (data(p*2)-flip);
            end
            if data(p*2) == flip
                flippedData(p*2) = data(p*2);
            end
            flippedData(p*2-1) = data(p*2-1);
        else
            flippedData(p*2)=nan;
            flippedData(p*2-1)=nan;
        end
    end
    
end